language:
  - android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

# fix for exiting with 137 code when executing "./gradlew clean assemble"
# which probable reason is lack of memory
# https://github.com/travis-ci/travis-ci/issues/2882#issuecomment-64949998
before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

script:
  - ./gradlew clean test
  - ./gradlew clean assemble

